In [3]:
import numpy as np
import pandas as pd


In [8]:
# Exercise 1
array1 = np.arange(1, 11)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
reshaped_array = array1.reshape(2, 5)
print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
# Exercise 2
array2= np.arange(1, 21)
print(array2)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [14]:
extracted = array2[5:16]
print(extracted)

[ 6  7  8  9 10 11 12 13 14 15 16]


In [9]:
# Exercise 3
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series
# fruit_series['pears'] = 4
# fruit_series

apples     3
bananas    2
oranges    1
dtype: int64

In [11]:
fruit_series['pears'] = 4
fruit_series

apples     3
bananas    2
oranges    1
pears      4
dtype: int64

In [17]:
# Exercise 4
data = {
    'name': ["Manu","Binoy","Sanu","Surya","Nandhu","Rani","Akhil","David","Ajay","Neethu"],
    'age': np.random.randint(20, 50, size=10),
    'gender': np.random.choice(['Male', 'Female'], size=10)
}

df = pd.DataFrame(data)
df

name  age  gender
0    Manu   30    Male
1   Binoy   20    Male
2    Sanu   40  Female
3   Surya   39    Male
4  Nandhu   20    Male
5    Rani   24    Male
6   Akhil   34    Male
7   David   25    Male
8    Ajay   20  Female
9  Neethu   28    Male

In [19]:
# Exercise 5
df['occupation'] = np.random.choice(['Programmer', 'Manager', 'Analyst'], size=10)
df

name  age  gender  occupation
0    Manu   30    Male  Programmer
1   Binoy   20    Male     Manager
2    Sanu   40  Female     Manager
3   Surya   39    Male  Programmer
4  Nandhu   20    Male     Analyst
5    Rani   24    Male     Manager
6   Akhil   34    Male     Analyst
7   David   25    Male  Programmer
8    Ajay   20  Female  Programmer
9  Neethu   28    Male     Analyst

In [21]:
# Exercise 6
age = df[df['age'] >= 30]
age

name  age  gender  occupation
0   Manu   30    Male  Programmer
2   Sanu   40  Female     Manager
3  Surya   39    Male  Programmer
6  Akhil   34    Male     Analyst

In [25]:
# Exercise 7

df.to_csv("data.csv")
read_df = pd.read_csv("data.csv")
read_df


Unnamed: 0    name  age  gender  occupation
0           0    Manu   30    Male  Programmer
1           1   Binoy   20    Male     Manager
2           2    Sanu   40  Female     Manager
3           3   Surya   39    Male  Programmer
4           4  Nandhu   20    Male     Analyst
5           5    Rani   24    Male     Manager
6           6   Akhil   34    Male     Analyst
7           7   David   25    Male  Programmer
8           8    Ajay   20  Female  Programmer
9           9  Neethu   28    Male     Analyst